# YOLOv12-Face Enhanced Configuration
# Intègre les dernières innovations 2025 pour la détection de visages
# Basé sur YOLOv12 avec attention mechanisms et vision transformer insights

# Parameters
nc: 1  # number of classes (face)
scales: # model compound scaling constants
  # [depth, width, max_channels]
  n: [0.50, 0.25, 1024]  # nano
  s: [0.50, 0.50, 1024]  # small
  m: [0.50, 1.00, 512]   # medium
  l: [1.00, 1.00, 512]   # large
  x: [1.00, 1.50, 512]   # extra-large

# YOLOv12-Face Enhanced Backbone
# Intègre Area Attention (A2) et R-ELAN de YOLOv12
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  
  # Enhanced C3k2 avec attention locale pour les petits visages
  - [-1, 2, C3k2, [256, False, 0.25]]  # 2
  - [-1, 1, SpatialAttention, [256]]  # 3 - Attention spatiale pour petits visages
  
  - [-1, 1, Conv, [256, 3, 2]] # 4-P3/8
  - [-1, 2, C3k2, [512, False, 0.25]]  # 5
  
  # Area Attention Module (A2) - Innovation YOLOv12
  - [-1, 1, A2Module, [512, 4]]  # 6 - Divise la feature map en 4 zones
  
  - [-1, 1, Conv, [512, 3, 2]] # 7-P4/16
  - [-1, 2, RELAN, [1024, True, 0.5]]  # 8 - Residual ELAN pour stabilité
  
  # Flash Attention pour efficacité
  - [-1, 1, FlashAttention, [1024, 8]]  # 9 - 8 heads
  
  - [-1, 1, Conv, [1024, 3, 2]] # 10-P5/32
  - [-1, 2, RELAN, [1024, True, 0.5]]  # 11
  
  # Cross-Stage Partial with Self-Attention (C2PSA) - YOLOv11 innovation
  - [-1, 1, C2PSA, [1024, 1]]  # 12
  
  - [-1, 1, SPPF, [1024, 3]]  # 13 - Kernel réduit pour visages

# YOLOv12-Face Enhanced Head
# Feature Pyramid amélioré avec attention cross-scale
head:
  # Upsample path avec attention
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]  # 14
  - [[-1, 8], 1, Concat, [1]]  # 15 - cat backbone P4
  
  # Cross-Scale Attention Fusion
  - [-1, 1, CrossScaleAttention, [512]]  # 16 - Fusion multi-échelle
  - [-1, 1, C3k2, [512, False, 0.5]]  # 17
  
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]  # 18
  - [[-1, 5], 1, Concat, [1]]  # 19 - cat backbone P3
  
  # Enhanced small face detection head
  - [-1, 1, MicroExpressionAttention, [256]]  # 20 - Pour micro-expressions
  - [-1, 1, C3k2, [256, False, 0.5]]  # 21 (P3/8-small)
  
  # Downsample path avec feature enhancement
  - [-1, 1, Conv, [256, 3, 2]]  # 22
  - [[-1, 17], 1, Concat, [1]]  # 23 - cat head P4
  - [-1, 1, C3k2, [512, False, 0.5]]  # 24 (P4/16-medium)
  
  - [-1, 1, Conv, [512, 3, 2]]  # 25
  - [[-1, 13], 1, Concat, [1]]  # 26 - cat head P5
  - [-1, 1, RELAN, [1024, True, 0.5]]  # 27 (P5/32-large)
  
  # Multi-Scale Adaptive Detection Head
  - [[21, 24, 27], 1, AdaptiveDetect, [nc, 256, 512, 1024]]  # Enhanced detect
